### ISSUE TITLE
get the volume level value

### ISSUE THREAD

**Issue by ChazrmaniH** [FinweLtd/orion360-sdk-pro-examples-android#10]
can we get and set the volume level for the player?

**Comment by ChazrmaniH** [comment]
any help?

**Comment by trantako** [comment]
Yes, for example via VideoPlayerWrapper.

Let's assume you have three virtual video screens in a 3D environment. For each virtual screen, you have created an OrionSprite, bound on OrionTexture to it, and feed video content to the texture from a VideoPlayerWrapper. In total, you have 3 sprites, 3 textures, 3 wrappers. Here we are interested in the wrappers:

    /** The left screen video player. */
    protected VideoPlayerWrapper mLeftVideoPlayer;

    /** The center screen video player. */
    protected VideoPlayerWrapper mCenterVideoPlayer;

    /** The right screen video player. */
    protected VideoPlayerWrapper mRightVideoPlayer;

Next, you initialize everything and start listening to device orientation changes and in the callback adjust the volume levels for each player so that the stream in the direction user is looking at is the loudest one. Here's a code sample:

    @Override
    public void onDeviceOrientationChanged(Quatf orientation) {
            Quatf camOrientation = mCamera.getRotation();
            Vec3f camAt = Vec3f.AXIS_FRONT.rotate(camOrientation);
            float camYaw = camAt.getYaw(); // yaw angle where user is looking at

            float leftVolume = (float) Math.sin(-camYaw);
            float centerVolume = (float) Math.cos(camYaw);
            float rightVolume = (float) Math.sin(camYaw);
            mLeftVideoPlayer.setVolume(leftVolume);
            mCenterVideoPlayer.setVolume(centerVolume);
            mRightVideoPlayer.setVolume(rightVolume);
//            Logger.logD(TAG, String.format(Locale.US,
//                    "Volume left=%f center=%f right=%f",
//                    leftVolume, centerVolume, rightVolume));
    }

**Comment by trantako** [comment]
There is now possibility to use ExoPlayer and get a handle to it. You can then call mExoPlayer.getVolume() or mExoPlayer.setVolume().

Closing the issue.
