### ISSUE TITLE
A number of questions:

### ISSUE THREAD

**Issue by AntonAFA** [FinweLtd/orion360-sdk-pro-examples-android#3]
- Do you support DRM playback?
- In your demo application i see that minimum android version is 19. Does this decision came from the application or is it SDK`s limitations?
- In your samples i did not see the example using DASH stream. Do you support it? 
- I have my own implementation of Exoplayer (2.3 version). Is it possible to pass it to your sdk instead of using your exoplayer wrapper/ maybe create another exoplayer wrapper that fits your needs?

Sorry for a lot of questions under one topic. but will be grate to have an answer

**Comment by trantako** [comment]
Hi Anton,

"Do you support DRM playback?"

Currently, no. DRM does not really work unless all parts of the distribution chain are protected, and rendering 360 video on display requires processing the video frames as (currently unprotected) OpenGL textures.

"In your demo application i see that minimum android version is 19. Does this decision came from the application or is it SDK`s limitations?"

Orion360 SDK Pro uses OpenGL ES 3.0, which was introduced in Android API level 18. That is the lowest where we can go with the Pro version (although, the current public version uses some other limiting APIs and hence the min level is there 19).

Orion360 SDK Basic uses OpenGL ES 2.0 and works with Android API level 14 and above.

"In your samples i did not see the example using DASH stream. Do you support it?"

Current public SDK supports only .mp4 streams and HLS adaptive streams, but since we have ExoPlayer as one of the backend options we could add support for MPEG-DASH, if needed.

"I have my own implementation of Exoplayer (2.3 version). Is it possible to pass it to your sdk instead of using your exoplayer wrapper/ maybe create another exoplayer wrapper that fits your needs?"

We have renamed the namespace for ExoPlayer that is embedded to Orion360 SDK Pro, meaning that you can include your own ExoPlayer variant in the same app. However, it is not yet possible to use that for feeding frames to Orion360 renderer, as we don't have a plug-in mechanism for video player backends. Please contact our support email to clarify your situation and we can find the best option forward.

**Comment by AntonAFA** [comment]
Thank you for your quick reply. In general, best solution for me will be passing my ExoplayerWrapper to your framework (actually i have a lot of important features in there) . I understand, that your own implementation of exoplayer have some 360/VR specified solutions. Also i understand, that you are currently using exoplayer 1.x version (and i am working with 2.3). I was wondering how complex could it be, to modify/extend my exoplayer to match your needs from it (i mean some custom implementation of VideoPlayerWrapper)?

**Comment by trantako** [comment]
Hi Anton,

We've discussed about this with the team and consider it a good idea to allow using customized versions of ExoPlayer for feeding decoded video frames to Orion360.

If all works out well, there will be probably be a new example soon that covers how to do this. We are currently in the process of updating the latest Orion360 version to the public repository and creating some new examples anyway.

**Comment by AntonAFA** [comment]
Good to hear it!  Waiting for your updates!
