### ISSUE TITLE
64-bit support requirement for Android apks

### ISSUE THREAD

**Issue by HassanImtiaz** [FinweLtd/orion360-sdk-pro-examples-android#7]
As per Google Play from August 1, 2019 all releases must be complaint with the Google Play 64-bit requirement. 
For Orion 360 android SDK, we only found **.so** files for **armeabi--v7a** & **x86**.
Orion 360 SDK build-script should be updated to support **armeabi--v8a** & **x86_64**.

Here is a reference to article:
https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by xserxses** [comment]
+1 same problem for us

**Comment by trantako** [comment]
The 64-bit build is in the works and will be released around mid-June.

**Comment by HassanImtiaz** [comment]
64-bit support is added in latest sdk version 'fi.finwe.orion360:orion360-sdk-basic:1.2.11'.
However while inflating OrionVideoView its giving an error: 
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lfi/finwe/log/Logger
Caused by: java.lang.ClassNotFoundException: Didn't find class "fi.finwe.log.Logger" on path:

**Comment by trantako** [comment]
HassanImtiaz, this repository is for the Pro version and you referred to the Basic version in your comment (...sdk-basic:1.2.11). With the Basic version, you should have these lines in your Gradle file:

    implementation 'fi.finwe.util:finwe-util:1.0.00'
    implementation 'fi.finwe.orion360:orion360-sdk-basic:1.2.11'

Class fi.finwe.log.Logger, which was not found, is in the package fi.finwe.util. Please check that your Gradle file has both lines.

***

Regarding the Pro version, the 64-bit build now exists and is being tested. It will be released via Bintray within a couple of days.

**Comment by HassanImtiaz** [comment]
Thanks it worked perfectly. I admit it should have been posted in basic version.
There is one observation that latest version 1.2.11 only supports **arm64-v8a**.
Its not supporting x86_64. Is there any particular reason for that, because managing multiple apks for different targets can be cumbersome.

**Comment by trantako** [comment]
The Basic version has only basic features and hence its binary size is fairly small. When it was originally developed, Intel was still trying to compete against ARM with their low-power Atom version of x86 chip. Hence, the Basic version has always supported armeabi-v7a, armeabi, x86, and mips architectures. 

Intel quit their efforts in April 2016. In addition, the Pro version is feature rich and has much larger binary size. Therefore, to minimize APK size, the Pro version has supported only the most relevant armeabi-v7a architecture and this has served us well.

However, we have now revised our policy due to Google's decision to require 64-bit builds in Play store.

For Basic version, this meant dropping out armeabi, x86, and mips architectures, which are pretty much obsolete in mobile today (and the devices using those architectures emulate ARM pretty well). You can still use the previous version of the SDK for building apks for these targets if necessary. We have added 64-bit ARM support, so now Basic is compiled against armeabi-v7a and arm64-v8a.

For Pro version, we added arm64-v8a in addition to existing armeabi-v7a.

There are currently no plans for x86_64 build. If you have a good case for that, contact us and we will consider it.
