### ISSUE TITLE
I got "UnsatisfiedLinkError: dlopen failed: library "libAudio360.so" not found"

### ISSUE THREAD

**Issue by 3ameration** [FinweLtd/orion360-sdk-pro-examples-android#8]
Hi, my application uses a different ExoPlayer version. so I changed the Orion version to be :

**implementation 'fi.finwe.orion360:orion360-sdk-pro:3.1.02.100'**

as you mentioned [Here](https://github.com/FinweLtd/orion360-sdk-pro-examples-android/commit/674a250699a1e560aadc66c8ae85cb028b67c3a3)

but when I open the activity that has the orion360 player I got the following error:
I got "UnsatisfiedLinkError: dlopen failed: library "libAudio360.so" not found"

can you help me to sort this out please?

Thank you

**Comment by trantako** [comment]
Hi,

V. 3.1.02.100 has native libraries built for armeabi-v7a and arm64-v8a and contains also "libAudio360.so" for these targets. Yet, the error says it cannot find it. 

Usually, this happens if you have another library in your project that includes native .so libs for a different target, say x86. Android will not mix libraries that were built for different targets. For a particular target, you need all .so libs or nothing.

Please check which targets you are compiling to. One simple way is to build a .jar from your project, rename it to .zip, extract to a folder, and then look at the contents under "jni" folder. All subfolders there should have the exact same list of .so files. Here's an example from V. 3.1.02.100:

![Screenshot 2020-05-22 at 9 11 45](https://user-images.githubusercontent.com/12032146/82636876-49356c80-9c0c-11ea-8373-e224ecd84832.png)

**Comment by 3ameration** [comment]
thank you for the clarification @trantako
