### ISSUE TITLE
sensor or listener is null caused a black screen

### ISSUE THREAD

**Issue by ChazrmaniH** [FinweLtd/orion360-sdk-pro-examples-android#9]
I got some of the bad reviews in play store from users who said that they got a black screen on the video player

I got one of these devices and realized that these devices don't support the rotation sensor

how can I disable the rotation sensor (disable the device rotation for the video and keep the finger movement ) to prevent the black screen?

I tried your sample project on the Input/Senor section, but I got a black screen as well
Thank you!

**Comment by trantako** [comment]
'Black screen' issues frequently produce bad reviews in app stores (not a surprise). If an app works on other devices but produces a black screen in the video view on a few selected models, then most of the time the root cause for this symptom is hardware's inability to decode a video file or stream: the combination of video resolution and bitrate is too much for its decoder (common), or it doesn't have the necessary decoder at all (rare). Especially, if the end-user can hear the soundtrack of the video file or stream but the video view is black, then you should suspect a problem with video decoding. To overcome this issue, you can either blacklist incapable devices from the store (easiest), provide an alternative video file or stream for low-end hardware (best for users), or prevent playback of such files or streams in the app's UI when running on low-end hardware (chance to explain why it doesn't work).

Often the problematic devices are targeted for the lowest price range and in addition to low-end video decoder they may also not have the typical movement sensors. Especially the gyroscope, which is necessary for 360-view panning, could be missing. While Orion360 can play 360 videos on hardware that does not have movement sensors (panning by touch only), this will not solve the problem if it is related to a video decoder's capabilities.

In your app's code, you could check if the device has an accelerometer, magnetometer, and gyroscope sensors. If not, you simply won't initialize sensor fusion and also won't bind it to any other Orion components. Of course, you can still use touch-based panning to allow panning the 360-view. Or, you could require in the manifest that all sensors are present, to prevent installation on incapable hardware.

However, as explained above, I am a bit skeptical if this will actually solve your issue with the black screen. If you have a device that suffers from this, I suggest you take a look at LogCat when you attempt to play a video file that causes problems. The video decoder may output errors there (these might not come from Orion360 or your app, so select "No filters" to see all the messages). You also might want to test video playback with a lower spec video file and see if the black screen issue disappears. 

For best image quality, we often want to use 4K or event higher video resolution, but there is still plenty of devices that do not decode 4K. There are also devices that do not work well with "non-standard" resolutions. For example, 1920x1080 might play OK but 2160x1080 produces a black screen. This used to be a common problem with devices whose maximum texture size is limited to 2048x2048.

The error you mentioned with the sample app seems to be related on playing content from the app's assets. If that doesn't work on your test hardware, you can change the code to play a video file from the device's mass memory. The sample app has plenty of examples of how to play video files from different locations/resources.

**Comment by ChazrmaniH** [comment]
thank you for your answer

I tried to change the source URI on the sample code and it's working fine on other devices, and I got the black screen on a low priced device.

I tried to play the same video using exoPlayer and its working fine even on the low price device, but with no rotation feature

can we do the same thing using Orion360? as it's using the exo-player at the end!

Thank you

**Comment by trantako** [comment]
If you are able to play a video file with ExoPlayer on a particular device, then it should be possible to play that file also with Orion360, as - just like you said - you can use ExoPlayer as the backend for decoding video frames.

One possible difference/problem could be the device's max texture size. ExoPlayer does not need a 3D environment for playing a video file, but Orion360 does since 360 content is rendered on screen using OpenGL ES. If the video's resolution is larger than the device's max texture size, then it fails to play.

To assist you further, we need the following information:
- What is the phone model that fails to play? Manufacturer, model, Android OS version
- What is the video source that fails to play? Can you provide a sample? If not, file type, encoding, resolution, fps etc. are useful information. 
- Is it a file or a video stream from the network? In case of latter, a .mp4 file or an HLS or other adaptive stream (e.g. m3u8)?

You should also check if a lower resolution file plays OK on that hardware. That helps in finding the cause of the issue. For example, you can try to play any 1280x720 MP4 video with Orion360 on the problem device to see if you get a black screen or video image.

**Comment by ChazrmaniH** [comment]
phone model: Huawei MediaPad T3 7, OS 6.0
video source that fails: https://sj5b5bjw.360meatech.com/hls/WillSmith/WillSmith.m3u8
m3u8

I think that's the issue, cuz I got the following Logs in the low price device :

**E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)**

E/MediaPlayer: setDataSource: IOException! uri=https://sj5b5bjw.360meatech.com/hls/WillSmith/WillSmith.m3u8
java.io.FileNotFoundException: No content provider: https://sj5b5bjw.360meatech.com/hls/WillSmith/WillSmith.m3u8

**Thank you for your help to sort out this issue**

**Comment by ChazrmaniH** [comment]
Hello @trantako, please keep me posted on further updates.
as the main feature of our app is depend on Orion360

Thank you
